package org.fluentjdbc;

import org.fluentjdbc.util.ExceptionUtil;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public class DatabaseInsertBuilder extends DatabaseStatement {

    private List<String> fieldNames = new ArrayList<>();
    private List<Object> parameters = new ArrayList<>();
    private DatabaseTable table;

    @Nullable
    private Object idValue;

    public DatabaseInsertBuilder(DatabaseTable table) {
        this.table = table;
    }

    public DatabaseInsertBuilder setField(String fieldName, @Nullable Object parameter) {
        this.fieldNames.add(fieldName);
        this.parameters.add(parameter);
        return this;
    }

    public DatabaseInsertBuilder setFields(List<String> fieldNames, List<Object> parameters) {
        this.fieldNames.addAll(fieldNames);
        this.parameters.addAll(parameters);
        return this;
    }

    public Object execute(Connection connection) {
        logger.debug(createInsertStatement());
        int autoGeneratedKeys = idValue == null ? Statement.RETURN_GENERATED_KEYS : 0;
        try (PreparedStatement stmt = connection.prepareStatement(createInsertStatement(), autoGeneratedKeys)) {
            bindParameters(stmt, parameters);
            stmt.executeUpdate();

            if (idValue != null) {
                return idValue;
            } else {
                return getGeneratedKey(stmt);
            }
        } catch (SQLException e) {
            throw ExceptionUtil.softenCheckedException(e);
        }
    }

    private String createInsertStatement() {
        String query = "insert into " + table.getTableName() +
                " (" + String.join(",", fieldNames)
                + ") values ("
                + String.join(",", repeat("?", fieldNames.size())) + ")";
        return query;
    }


    private long getGeneratedKey(PreparedStatement stmt) throws SQLException {
        try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
            generatedKeys.next();
            return generatedKeys.getLong(1);
        }
    }

    public DatabaseInsertBuilder setPrimaryKey(String idField, @Nullable Object idValue) {
        if (idValue != null) {
            this.idValue = idValue;
            setField(idField, idValue);
        }
        return this;
    }
}
