name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: mvn test --batch-mode --fail-at-end
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
    - name: Coveralls.io coverage report
      run: mvn jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls }}
      
